# Generated by Django 4.1.3 on 2022-11-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tareas', '0003_rename_apellido_usuario_apellidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='designado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecompleto', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
